# Performing Calculations Using Vectors and Matrixes
## Understanding scalar and vector operations

In [1]:
import numpy as np

In [2]:
myShort = np.short(15)
print(myShort)

15


In [3]:
myVect = np.array([1, 2, 3, 4])
print(myVect)

[1 2 3 4]


In [4]:
myVect = np.arange(1, 10, 2)
print(myVect)

[1 3 5 7 9]


In [5]:
myVect = np.array(np.int16([1, 2, 3, 4]))
print(myVect)

[1 2 3 4]


In [6]:
print(type(myVect[0]))

<class 'numpy.int16'>


In [7]:
myVect = np.ones(4, dtype=np.int16)
print(myVect)

[1 1 1 1]


In [8]:
myVect = np.array([1, 2, 3, 4])
myVect += 1
print(myVect)

[2 3 4 5]


In [9]:
myVect = np.array([1, 2, 3, 4])
myVect -= 1
print(myVect)

[0 1 2 3]


In [10]:
myVect = np.array([1, 2, 3, 4])
myVect = 2 ** myVect
print(myVect)

[ 2  4  8 16]


In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [12]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


## Performing vector multiplication

In [13]:
myVect = np.array([1, 2, 3, 4])
print(myVect * myVect)
print(np.multiply(myVect, myVect))

[ 1  4  9 16]
[ 1  4  9 16]


In [14]:
print(myVect.dot(myVect))

30


## Creating a matrix is the right way to start

In [15]:
myMatrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
myMatrix = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(myMatrix)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
print(myMatrix[0, 1, 1])

4


In [18]:
myMatrix = np.ones([4,4], dtype=np.int32)
print(myMatrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
myMatrix = np.ones([4,4,4], dtype=np.bool)
print(myMatrix)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [20]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(type(myMatrix))

<class 'numpy.matrix'>


## Multiplying matrixes

In [22]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [23]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[3,4,5],[5,6,7]])

print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [24]:
a = np.mat([[1,2,3],[4,5,6]])
b = np.mat([[1,2,3],[3,4,5],[5,6,7]])

print(a*b)

[[22 28 34]
 [49 64 79]]


## Defining advanced matrix operations

In [25]:
changeIt = np.array([1,2,3,4,5,6,7,8])
print(changeIt)

changeIt = changeIt.reshape(2,4)
print(changeIt)

changeIt = changeIt.reshape(2,2,2)
print(changeIt)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
changeIt = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(changeIt)

changeIt = np.transpose(changeIt)
print(changeIt)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [27]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b), np.identity(2)))

True


# Creating Combinations the Right Way
## Distinguishing permutations

In [29]:
a = np.array([1,2,3])
print(np.random.permutation(a))

[3 1 2]


In [30]:
from itertools import permutations

a = np.array([1,2,3])

for p in permutations(a):
    print(p)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


## Shuffling combinations

In [31]:
from itertools import combinations

a = np.array([1,2,3,4])

for comb in combinations(a, 2):
    print(comb)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [32]:
import random

pool = []

for comb in combinations(a, 2):
    pool.append(comb)

print(random.sample(pool, 3))

[(1, 4), (3, 4), (2, 3)]


## Facing repetitions

In [33]:
a = np.array([1,2,3,4,5,6,6,7,7,1,2,3])
b = np.array(list(set(a)))

print(b)

[1 2 3 4 5 6 7]
